---
title: "regression"
author: "Chong Hu"
date: "12/6/2019"
output: html_document
---


```{r}
knitr::opts_chunk$set(echo = TRUE)
```


# data load

```{r}
train.df <- na.omit(read.csv("../data/train.csv", header = T))
test.df <- na.omit(read.csv("../data/test.csv", header = T))
train.df$Genre = as.factor(train.df$Genre)
train.df$Sequel = as.factor(train.df$Sequel)
test.df$Genre = factor(test.df$Genre, levels = levels(train.df$Genre))
test.df$Sequel = factor(test.df$Sequel, levels = levels(train.df$Sequel))
conventional_train.df = na.omit(train.df[, c("Ratings", "Genre", "Gross", "Budget", "Screens", "Sequel")])
conventional_test.df = na.omit(test.df[, c("Ratings", "Genre", "Gross", "Budget", "Screens", "Sequel")])
socialmedia_train.df = na.omit(train.df[, c("Ratings", "Sentiment", "Views", "Likes", "Dislikes", "Comments", "Aggregate.Followers")])
socialmedia_test.df = na.omit(test.df[, c("Ratings", "Sentiment", "Views", "Likes", "Dislikes", "Comments", "Aggregate.Followers")])
```

# simple linear regression

Just start regression, not the final model

## Conventional features

```{r}
num2factor <- function(val)
{
  if(val<=4.9){
    return("Poor")
  }else if(val<=6.4){
    return("Average")
  }else if(val<=8.9){
    return("Good")
  }else if(val<=10){
    return("Excellent")
  }
}

```

```{r}
conventional.lm = lm(Ratings ~ ., data = conventional_train.df)
conventional.pred = predict(conventional.lm, conventional_test.df, type="response")
mean((conventional.pred - conventional_test.df$Ratings)^2)
# soft accuracy
sum(abs(conventional.pred - conventional_test.df$Ratings) < 1)/nrow(conventional_test.df)

# classification
conventional.pred<-  mapply(num2factor, conventional.pred)
conventional_test.df$asLabel <- mapply(num2factor, conventional_test.df$Ratings)
sum(conventional.pred==conventional_test.df$asLabel)/nrow(conventional_test.df)
```

```{r}
summary(conventional.lm)
plot(conventional.lm)
```

## Soical Media features

```{r}
socialmedia.lm = lm(Ratings ~ ., data = socialmedia_train.df)
socialmedia.pred = predict(socialmedia.lm, socialmedia_test.df)
mean((socialmedia.pred - socialmedia_test.df$Ratings)^2)
# soft accuracy
sum(abs(socialmedia.pred - socialmedia_test.df$Ratings) < 1)/nrow(socialmedia_test.df)

# classification
socialmedia.pred <-  mapply(num2factor, socialmedia.pred)
socialmedia_test.df$asLabel <- mapply(num2factor, socialmedia_test.df$Ratings)
sum(socialmedia.pred==socialmedia_test.df$asLabel)/nrow(socialmedia_test.df)
```

```{r}
summary(socialmedia.lm)
plot(socialmedia.lm)
```

# Generalised linear regression model

## Conventional features

```{r}
conventional.glm = glm(Ratings ~ ., data = conventional_train.df, family = Gamma (link = "log"))
conventional.pred = predict(conventional.glm, conventional_test.df, type="response")
mean((conventional.pred - conventional_test.df$Ratings)^2)

```


```{r}
summary(conventional.glm)
plot(conventional.glm)
```

```{r}

# soft accuracy
sum(abs(conventional.pred - conventional_test.df$Ratings) < 1)/nrow(conventional_test.df)

# classification
conventional.pred<-  mapply(num2factor, conventional.pred)
conventional_test.df$asLabel <- mapply(num2factor, conventional_test.df$Ratings)
sum(conventional.pred==conventional_test.df$asLabel)/nrow(conventional_test.df)
```

## Soical Media features

```{r}
socialmedia.glm = glm(Ratings ~ ., data = socialmedia_train.df, family =  Gamma (link = "log"))
socialmedia.pred = exp(predict(socialmedia.glm, socialmedia_test.df))
mean((socialmedia.pred - socialmedia_test.df$Ratings)^2)

```

```{r}
summary(socialmedia.glm)
plot(socialmedia.glm)
```

```{r}
# soft accuracy
sum(abs(socialmedia.pred - socialmedia_test.df$Ratings) < 1)/nrow(socialmedia_test.df)

# classification
socialmedia.pred <-  mapply(num2factor, socialmedia.pred)
socialmedia_test.df$asLabel <- mapply(num2factor, socialmedia_test.df$Ratings)
sum(socialmedia.pred==socialmedia_test.df$asLabel)/nrow(socialmedia_test.df)
```


# Generalised additive regression model

## Conventional features

```{r}
library(gam)
conventional.gam = gam(Ratings ~ ., data = conventional_train.df, family = Gamma (link = "inverse"))
conventional.pred = predict(conventional.gam, conventional_test.df, type="response")
mean((conventional.pred - conventional_test.df$Ratings)^2)

```


```{r}
summary(conventional.gam)
plot(conventional.gam)
```

```{r}

# soft accuracy
sum(abs(conventional.pred - conventional_test.df$Ratings) < 1)/nrow(conventional_test.df)

# classification
conventional.pred<-  mapply(num2factor, conventional.pred)
conventional_test.df$asLabel <- mapply(num2factor, conventional_test.df$Ratings)
sum(conventional.pred==conventional_test.df$asLabel)/nrow(conventional_test.df)
```

## Soical Media features

```{r}
socialmedia.gam = gam(Ratings ~ ., data = socialmedia_train.df, family =  Gamma (link = "inverse"))
socialmedia.pred = 1/predict(socialmedia.gam, socialmedia_test.df)
mean((socialmedia.pred - socialmedia_test.df$Ratings)^2)

```

```{r}
summary(socialmedia.gam)
plot(socialmedia.gam)
```

```{r}
# soft accuracy
sum(abs(socialmedia.pred - socialmedia_test.df$Ratings) < 1)/nrow(socialmedia_test.df)

# classification
socialmedia.pred <-  mapply(num2factor, socialmedia.pred)
socialmedia_test.df$asLabel <- mapply(num2factor, socialmedia_test.df$Ratings)
sum(socialmedia.pred==socialmedia_test.df$asLabel)/nrow(socialmedia_test.df)
```
