---
title: "Data Visiualization"
author: "Chong HU"
date: "12/8/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library("readxl")
data1 = read_excel("1415CSM_dataset.xlsx")
i=1
asLabel=""
for (val in data1$Ratings) {
  if(val<=5.2){
    asLabel[i]="Poor"
  }else if(val<=6.4){
    asLabel[i]="Average"
  }else if(val<=7.2){
    asLabel[i]="Good"
  }else if(val<=10){
    asLabel[i]="Excellent"
  }
  i=i+1
}
# print(asLabel)
data.df = data.frame(data1,asLabel)
data.df = na.omit(data.df)
data.df$Genre = as.factor(data.df$Genre)
data.df$Sequel = as.factor(data.df$Sequel)
```

```{r}
library(ggplot2)
library(dplyr)
library(forcats)
gg <- ggplot(data.df, aes(x=log(Budget), y=Gross)) + 
  geom_point(aes(col=asLabel, size=Genre)) + 
  geom_smooth(method="loess", se=F) + 
  labs(subtitle="Gross Vs Budget", 
       y="Gross", 
       x="Budget", 
       title="Scatterplot", 
       caption = "Source: conventional and soical media dataset")
gg
```

```{r}
library(reshape2)
nums <- unlist(lapply(data.df, is.numeric))  
num.df <- data.df[, nums]
num.df <- subset(num.df, select = - c(Year))
cor.mat <- round(cor(num.df), 2)
cor.mat[lower.tri(cor.mat)]<- NA
upper.mat <- cor.mat
upper.melt <- melt(upper.mat, na.rm = TRUE)
p <- ggplot(upper.melt, aes(Var2, Var1, fill = value))+
   geom_tile(color = "white")+
 scale_fill_gradient2(low = "#6D9EC1", high = "#E46726", mid = "white", 
   midpoint = 0, limit = c(-1,1), space = "Lab", 
    name="Pearson\nCorrelation") +
  theme_minimal()+ # minimal theme
 theme(axis.text.x = element_text(angle = 45, vjust = 1, 
    size = 12, hjust = 1))+
 coord_fixed()+
geom_text(aes(Var2, Var1, label = value), color = "black", size = 4) +
theme(
  axis.title.x = element_blank(),
  axis.title.y = element_blank(),
  panel.border = element_blank(),
  panel.background = element_rect(fill = "#ebf5f5",
                                colour = "#dce1e7",
                                size = 0.25),

  panel.grid.minor = element_line(size = 0.25, linetype = 'solid',
                                colour = "white"),
  axis.ticks = element_blank(),
  legend.justification = c(1, 0),
  legend.position = c(0.6, 0.7),
  legend.direction = "horizontal")+
  guides(fill = guide_colorbar(barwidth = 7, barheight = 1,
                title.position = "top", title.hjust = 0.5))
p
```


```{r}
p1 <-ggplot(data.df, aes(x=Ratings)) +
  geom_histogram(aes(y=..density..), colour="grey", alpha=0.5)+
  geom_density(alpha=.4, fill="lightblue")+
  xlab("") +
  theme(axis.text.x=element_blank(),
        axis.ticks.x=element_blank())
p2 <-ggplot(data.df, aes(y=Ratings))+
  geom_boxplot(fill = "lightblue", color = "black") + 
  coord_flip() +
  theme_classic() +
  xlab("") +
  theme(axis.text.y=element_blank(),
        axis.ticks.y=element_blank())

library(patchwork)
p1 + p2 + plot_layout(nrow = 2, heights = c(5, 1))
```

```{r}
gross_p <- ggplot(data.df, aes(x=factor(asLabel, level = c('Poor', 'Average', 'Good', 'Excellent')), y=Gross, fill=asLabel)) + 
  geom_boxplot()+
  theme_classic()+
  theme(axis.text.x = element_text(angle = 0, hjust = 1))+
  labs(x="Label")
gross_p


```

```{r}
budget_p <- ggplot(data.df, aes(x=factor(asLabel, level = c('Poor', 'Average', 'Good', 'Excellent')), y=Budget, fill=asLabel)) + 
  geom_boxplot()+
  theme_classic()+
  theme(axis.text.x = element_text(angle = 0, hjust = 1))+
  labs(x="Label")
budget_p
```


```{r}
screens_p <- ggplot(data.df, aes(x=factor(asLabel, level = c('Poor', 'Average', 'Good', 'Excellent')), y=Screens, fill=asLabel)) + 
  geom_boxplot()+
  theme_classic()+
  theme(axis.text.x = element_text(angle = 0, hjust = 1))+
  labs(x="Label")
screens_p
```
```{r}
views_p <- ggplot(data.df, aes(x=factor(asLabel, level = c('Poor', 'Average', 'Good', 'Excellent')), y=Views, fill=asLabel)) + 
  geom_boxplot()+
  theme_classic()+
  theme(axis.text.x = element_text(angle = 0, hjust = 1))+
  labs(x="Label")
views_p
```




```{r}
likes_p <- ggplot(data.df, aes(x=factor(asLabel, level = c('Poor', 'Average', 'Good', 'Excellent')), y=log(Likes), fill=asLabel)) + 
  geom_boxplot()+
  theme_classic()+
  theme(axis.text.x = element_text(angle = 0, hjust = 1))+
  labs(x="Label")
likes_p
```

```{r}
dislike_p <- ggplot(data.df, aes(x=factor(asLabel, level = c('Poor', 'Average', 'Good', 'Excellent')), y=log(Dislikes), fill=asLabel)) + 
  geom_boxplot()+
  theme_classic()+
  theme(axis.text.x = element_text(angle = 0, hjust = 1))+
  labs(x="Label")
dislike_p
```

```{r}
sentiment_p <- ggplot(data.df, aes(x=factor(asLabel, level = c('Poor', 'Average', 'Good', 'Excellent')), y=Sentiment, fill=asLabel)) + 
  geom_boxplot()+
  theme_classic()+
  theme(axis.text.x = element_text(angle = 0, hjust = 1))+
  labs(x="Label")
sentiment_p
```
```{r}
comment_p <- ggplot(data.df, aes(x=factor(asLabel, level = c('Poor', 'Average', 'Good', 'Excellent')), y=log(Comments), fill=asLabel)) + 
  geom_boxplot()+
  theme_classic()+
  theme(axis.text.x = element_text(angle = 0, hjust = 1))+
  labs(x="Label")
comment_p
```
```{r}
genre_p <- ggplot(data.df, aes(Genre, ..count..)) + 
  geom_bar(aes(fill = factor(asLabel, level = c('Poor', 'Average', 'Good', 'Excellent'))), position = "dodge")+
  theme_classic()+
  theme(axis.text.x = element_text(angle = 0, hjust = 1))+
  labs(fill = "Label")
genre_p
```

```{r}
sequel_p <- ggplot(data.df, aes(Sequel, ..count..)) + 
  geom_bar(aes(fill = factor(asLabel, level = c('Poor', 'Average', 'Good', 'Excellent'))), position = "dodge")+
  theme_classic()+
  theme(axis.text.x = element_text(angle = 0, hjust = 1))+
  labs(fill = "Label")
sequel_p
```

